# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish snapshot

on:
  push:
    branches:
      - bleeding
      - bleeding-*

jobs:
  publish-snapshot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: powernukkit-snapshots
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Publish snapshot
      run: mvn --no-transfer-progress -B deploy -Dgpg.skip=true -DskipTests=false
      env:
        MAVEN_USERNAME: ${{ secrets.POWERNUKKIT_SNAPSHOT_USER }}
        MAVEN_PASSWORD: ${{ secrets.POWERNUKKIT_SNAPSHOT_PASSWORD }}
    - name: Trigger powernukkit-versions.json update
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.POWERNUKKIT_VERSIONS_TOKEN }}
        event-type: update-versions-json
        repository: PowerNukkit/powernukkit-version-aggregator
